version: "3.8"
services:
  mongodb:
  # These service name will also be memorised by docker.
  # We can use the name in place of IP to access it.
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: username
      # MONGO_INITDB_ROOT_PASSWORD: password
    # env_file
      # - ./env/mongo.env
  node_server:
    build: ./
    # build:
      # context: ./
      # dockerfile: Dockerfile
      # It is not needed if the file name is Dockerfile.
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/src
    environment:
      DBIP: mongodb
    depends_on:
      - mongodb
volumes:
  data:


# named volues should be specified here.