apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: movies-app
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 80