apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  labels:
    name: node-server-service
    app: movies-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: server-pod
    app: movies-app
