apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    name: server-pod
    app: movies-app
spec:
  containers:
    - name: server
      image: gokupronoob/docker-node
      ports:
        - containerPort: 80