apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  labels:
    name: node-server-service
    app: movies-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: server-pod
    app: movies-app
